version: "3.9"

services:
  test-db:
    container_name: test-db
    image: mysql:8.0
    restart: always
    ports:
      - "3399:3306"
    environment:
      MYSQL_DATABASE: istock
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    networks:
      - test

  test-redis:
    container_name: test-redis
    image: redis
    restart: always
    ports:
      - "6399:6379"
    networks:
      - test

networks:
  test:
    driver: bridge