INSERT INTO role (id, role_name)
SELECT * FROM (SELECT 1, "ROLE_ADMIN") AS tmp
WHERE NOT EXISTS(SELECT * FROM role WHERE role_name="ROLE_ADMIN");

INSERT INTO role (id, role_name)
SELECT * FROM (SELECT 2, "ROLE_USER") AS tmp
WHERE NOT EXISTS(SELECT * FROM role WHERE role_name="ROLE_USER");